SELECT
    V.CUSTOMER_ID AS customer_id,
    COUNT(*) AS count_no_trans
FROM
    VISITS V
LEFT JOIN
    TRANSACTIONS T
ON 
    V.VISIT_ID = T.VISIT_ID
WHERE
    T.TRANSACTION_ID IS NULL
GROUP BY V.CUSTOMER_ID;
