SELECT
    IFNULL(ROUND((COUNT(DISTINCT SESSION_ID)/COUNT(DISTINCT USER_ID)), 2), 0.00) AS "average_sessions_per_user"
FROM 
    ACTIVITY
WHERE 
    (ACTIVITY_DATE > '2019-06-27' AND ACTIVITY_DATE <= '2019-07-27');
