SELECT 
    ACTIVITY_DATE AS 'day', 
    COUNT(DISTINCT USER_ID) AS 'active_users'
FROM 
    ACTIVITY
WHERE 
    (ACTIVITY_DATE > "2019-06-27" AND ACTIVITY_DATE <= "2019-07-27")
GROUP BY 
    ACTIVITY_DATE;
