SELECT
    ROUND(AVG(
        CASE
            WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1
            ELSE 0
        END
    ) * 100.00, 2) AS immediate_percentage
FROM
    DELIVERY
WHERE (CUSTOMER_ID, ORDER_DATE) IN (
    SELECT CUSTOMER_ID, MIN(ORDER_DATE) FROM DELIVERY
    GROUP BY CUSTOMER_ID
);
