SELECT
    S.USER_ID,
    ROUND(AVG(CASE
        WHEN C.ACTION = 'confirmed' THEN 1.00
        ELSE 0.00
    END), 2) AS CONFIRMATION_RATE
FROM
    SIGNUPS S
LEFT JOIN
    CONFIRMATIONS C
ON
    S.USER_ID = C.USER_ID
GROUP BY S.USER_ID;
    