SELECT
    T1.MACHINE_ID,
    ROUND(AVG(T2.timestamp - T1.timestamp)::DECIMAL, 3) AS processing_time
FROM
    ACTIVITY T1
JOIN
    ACTIVITY T2
ON
    T1.MACHINE_ID = T2.MACHINE_ID
AND T1.PROCESS_ID = T2.PROCESS_ID
AND T1.ACTIVITY_TYPE = 'start' AND T2.ACTIVITY_TYPE = 'end'
GROUP BY T1.MACHINE_ID
-- ORDER BY T1.MACHINE_ID;