SELECT DISTINCT
    A.ACTOR_ID AS 'actor_id',
    D.DIRECTOR_ID AS 'director_id'
    
FROM 
    ACTORDIRECTOR A
    INNER JOIN
    ACTORDIRECTOR D
    
    ON A.TIMESTAMP = D.TIMESTAMP


GROUP BY A.ACTOR_ID, D.DIRECTOR_ID
HAVING COUNT(*) >= 3;
