SELECT
    DISTINCT A.ACCOUNT_ID AS 'account_id'
FROM
    LOGINFO A
JOIN
    LOGINFO B
ON 
    A.ACCOUNT_ID = B.ACCOUNT_ID
WHERE
    A.IP_ADDRESS <> B.IP_ADDRESS
    AND 
    (A.LOGOUT >= B.LOGIN AND A.LOGOUT <= B.LOGOUT
    OR 
    B.LOGOUT >= A.LOGIN AND B.LOGOUT <= A.LOGOUT);

    